### ISSUE TITLE
Support XML import with text markup and internal resource references

### ISSUE THREAD

**Issue by benjamingeer** [dasch-swiss/knora-py#27]
I would like to be able to submit an XML bulk import file to knora-py, including text with markup containing links that point to other resources created by the same import file. This could be done the way it's done in the Knora API v1 bulk import:

```
<resource label="thing01"
  restype="Thing"
  permissions="res-default"
  unique_id="thing01" />
<resource label="thing02"
  restype="Thing"
  permissions="res-default"
  unique_id="thing02">
    <text-prop name="hasText"
      mapping="http://rdfh.ch/standoff/mappings/StandardMapping"
      permissions="prop-default">
      <text>This text links to another <a class="salsah-link" href="ref:thing01">resource</a>.
    </text>
</resource>
```

Then knora-py would:

1. Create `thing01` first.
2. Replace `ref:thing01` with the IRI of `thing01` before creating `thing02`.

We would just need a way to tell knora-py that `<a class="salsah-link">` represents a link property in the standard mapping. Maybe this could just be specified in the input file:

```
<standoffLinkElements>
  <mapping iri="http://rdfh.ch/standoff/mappings/StandardMapping">
    <element name="a" class="salsah-link" linkAttribute="href" />
  </mapping>
</standoffLinkElements>
```

Then knora-py would know that if a text value uses that mapping and contains an `<a class="salsah-link">`, and the `href` attribute starts with `ref:`, it should replace the contents of `href` with the IRI of the resource with that ID.

@tobiasschweizer Does this make sense to you?

**Comment by subotic** [comment]
@benjamingeer Could you please move this issue to YouTrack?

**Comment by benjamingeer** [comment]
Moved to https://dasch.myjetbrains.com/youtrack/issue/DSP-471.
